import assert from 'node:assert/strict';
import fs from 'node:fs';

const server = fs.readFileSync('server/index.ts', 'utf8');

// WORK-01: Google OAuth + session endpoints
assert.match(server, /app\.get\('\/api\/auth\/google'/, 'server must expose Google OAuth redirect endpoint');
assert.match(server, /app\.get\('\/api\/auth\/callback'/, 'server must expose Google OAuth callback endpoint');
assert.match(server, /app\.get\('\/api\/auth\/me'/, 'server must expose auth/me endpoint');
assert.match(server, /app\.post\('\/api\/auth\/logout'/, 'server must expose logout endpoint');
assert.match(server, /HttpOnly/, 'session cookies must be httpOnly');
assert.match(server, /credentials:\s*true/, 'CORS must allow credentialed auth requests');
assert.match(server, /GOOGLE_CLIENT_ID/, 'Google OAuth must be env-driven');
assert.match(server, /GOOGLE_CLIENT_SECRET/, 'Google OAuth must be env-driven');
assert.match(server, /GOOGLE_OAUTH_NOT_CONFIGURED/, 'OAuth endpoints must fail safely without real credentials');
assert.match(server, /FRONTEND_URL/, 'OAuth callback must redirect back to the frontend origin');
assert.match(server, /res\.redirect\(getFrontendRedirectUrl\(req,\s*redirectTo\)\)/, 'OAuth callback must not redirect relative paths on the API origin');

// WORK-02: Polar webhook HMAC verification + premium persistence
assert.match(server, /app\.post\('\/api\/polar\/webhook'/, 'server must expose Polar webhook endpoint');
assert.match(server, /POLAR_WEBHOOK_SECRET/, 'Polar webhook verification must be env-driven');
assert.match(server, /webhook-id/, 'Polar webhook verification must use the Standard Webhooks id header');
assert.match(server, /webhook-timestamp/, 'Polar webhook verification must use the Standard Webhooks timestamp header');
assert.match(server, /Buffer\.from\(`\$\{webhookId\}\.\$\{webhookTimestamp\}\.`\)/, 'Polar webhook must sign id.timestamp.payload');
assert.match(server, /crypto\.createHmac\('sha256',\s*polarWebhookSecretBytes\(\)\)/, 'Polar webhook must use HMAC-SHA256 with decoded Standard Webhooks secret');
assert.match(server, /crypto\.timingSafeEqual/, 'signature compare must be timing-safe');
assert.match(server, /POLAR_SIGNATURE_INVALID/, 'invalid webhook signatures must be rejected');
assert.match(server, /order\.paid/, 'one-time Polar purchases must be granted on paid order events');
assert.doesNotMatch(server, /order\.created', 'checkout\.created/, 'Polar webhook must not grant premium on pre-payment created events');
assert.match(server, /subscription\.canceled/, 'Polar subscription cancellation events must be handled');
assert.match(server, /premiumByEmail/, 'premium state must be stored server-side by email');
assert.match(server, /subscriptionExpiresAt/, 'monthly premium must have an expiry');
assert.match(server, /oneTimePasses/, 'one-time premium passes must be tracked');
assert.match(server, /STARTUP_CONFIG_ERRORS/, 'production startup must fail fast on missing launch configuration');
assert.match(server, /SESSION_SECRET = process\.env\.SESSION_SECRET \|\| \(IS_PRODUCTION \? '' : crypto\.randomBytes/, 'production must not generate ephemeral session secrets');
assert.match(server, /CORS_ALLOWED_ORIGINS/, 'CORS origins must be allowlisted for credentialed requests');
assert.match(server, /products:\s*\[selectedProductId\]/, 'Polar checkout must use server-selected product allowlist');
assert.match(server, /configuredPolarCheckoutUrl/, 'checkout endpoint must prefer configured Polar checkout links');
assert.match(server, /source:\s*'configured_link'/, 'checkout response must identify configured checkout link source');
assert.match(server, /isPolarCheckoutUrl/, 'server must validate configured Polar checkout links');
assert.match(server, /currency:\s*POLAR_CHECKOUT_CURRENCY/, 'Polar checkout must request KRW catalog pricing');
assert.doesNotMatch(server, /prices:\s*polarCheckoutPrices/, 'Polar checkout must not override catalog one-time/subscription prices with ad-hoc prices');
assert.match(server, /customer_ip_address:\s*clientIpAddress\(req\)/, 'Polar checkout must forward customer IP for currency selection');
assert.match(server, /return_url:/, 'Polar checkout must use return_url for current checkout schema');
assert.doesNotMatch(server, /cancel_url:\s*POLAR_CHECKOUT_CANCEL_URL/, 'Polar checkout create payload must not rely on deprecated cancel_url');
assert.match(server, /POLAR_CHECKOUT_CURRENCY/, 'Polar checkout currency must be env-driven');
assert.match(server, /POLAR_PRODUCT_ID_NOT_ALLOWED/, 'clients must not be allowed to submit arbitrary Polar product IDs');
assert.match(server, /UUID_PATTERN/, 'server must validate Polar product IDs as UUIDs before calling Polar');
assert.match(server, /POLAR_PRODUCT_ID_INVALID/, 'checkout must fail locally when a configured Polar product ID is malformed');
assert.match(server, /must be a valid Polar product UUID/, 'production validation must reject malformed Polar product IDs');
const envExample = fs.readFileSync('.env.example', 'utf8');
const env = envExample;
const compose = fs.readFileSync('docker-compose.yml', 'utf8');
assert.match(envExample, /POLAR_ONE_TIME_PRODUCT_ID=3c5002d7-b5aa-4c8d-8fe4-433e8d46c239/, 'env example must wire the Polar one-time KRW product ID');
assert.match(envExample, /POLAR_MONTHLY_PRODUCT_ID=d7cd5993-4d33-46d9-8ba6-994c70b527f9/, 'env example must wire the Polar monthly KRW product ID');
assert.match(envExample, /POLAR_CHECKOUT_CURRENCY=krw/, 'env example must request KRW checkout currency');
assert.match(envExample, /POLAR_ONE_TIME_CHECKOUT_URL=https:\/\/buy.polar.sh\/polar_cl_aGzorRvqZUgPJEt53EUCH6VZcuSyjV1hOrjBQ473ZZp/, 'env example must wire the Polar one-time checkout link');
assert.match(envExample, /POLAR_MONTHLY_CHECKOUT_URL=https:\/\/buy.polar.sh\/polar_cl_FFPmuDyi5Tp6g3NXSZWDenTjVJT2HYSN2UQu90uqaio/, 'env example must wire the Polar monthly checkout link');
assert.match(compose, /POLAR_ONE_TIME_CHECKOUT_URL:-https:\/\/buy\.polar\.sh\/polar_cl_aGzorRvqZUgPJEt53EUCH6VZcuSyjV1hOrjBQ473ZZp/, 'docker compose must pass through the Polar one-time checkout link default');
assert.match(compose, /POLAR_MONTHLY_CHECKOUT_URL:-https:\/\/buy\.polar\.sh\/polar_cl_FFPmuDyi5Tp6g3NXSZWDenTjVJT2HYSN2UQu90uqaio/, 'docker compose must pass through the Polar monthly checkout link default');
assert.match(compose, /POLAR_ONE_TIME_PRODUCT_ID:-3c5002d7-b5aa-4c8d-8fe4-433e8d46c239/, 'docker compose must pass through the Polar one-time product ID default');
assert.match(compose, /POLAR_MONTHLY_PRODUCT_ID:-d7cd5993-4d33-46d9-8ba6-994c70b527f9/, 'docker compose must pass through the Polar monthly product ID default');
assert.match(server, /polarWebhookEvents/, 'Polar webhook events must be persisted for idempotency');
assert.match(server, /hasProcessedPolarEvent/, 'Polar webhook handler must reject duplicate deliveries');
assert.match(server, /GOOGLE_REDIRECT_URI is required/, 'production validation must require explicit Google redirect URI');
assert.match(server, /ALL_ZERO_UUID/, 'production validation must reject placeholder product UUIDs');
assert.match(server, /isPlaceholderConfigValue\(POLAR_ACCESS_TOKEN/, 'production validation must reject placeholder Polar access tokens');
assert.match(server, /isPlaceholderConfigValue\(POLAR_WEBHOOK_SECRET/, 'production validation must reject placeholder Polar webhook secrets');
assert.match(server, /POLAR_ONE_TIME_PRODUCT_ID must be a valid Polar product UUID/, 'production validation must require a valid one-time product UUID while one-time plan is visible');
assert.match(server, /POLAR_MONTHLY_PRODUCT_ID must be a valid Polar product UUID/, 'production validation must require a valid monthly product UUID while monthly plan is visible');
assert.match(server, /const idempotencyKey = deliveryId/, 'Polar webhook idempotency must use the Standard Webhooks delivery id');
assert.doesNotMatch(server, /purchase\.eventId/, 'Polar webhook idempotency must not use arbitrary nested payload ids');
assert.match(server, /Ignoring grant for unconfigured productId/, 'unknown Polar products must be ignored instead of granted');
assert.doesNotMatch(server, /isOneTime \|\| !POLAR_MONTHLY_PRODUCT_ID/, 'missing monthly product must not make arbitrary products grant one-time access');

// WORK-08: reusable server-side premium enforcement
assert.match(server, /function requirePremium/, 'premium check must be reusable middleware');
assert.match(server, /const isAdmin = isAdminEmail\(session\?\.user\.email\)/, 'admin users must be detected in premium checks server-side');
assert.match(server, /if \(isAdmin \|\| premium\.isPremium\)/, 'premium middleware must bypass checks for admin/premium users');
assert.match(server, /FREE_DAILY_LIMIT_EXCEEDED/, 'premium feature usage must return free-tier daily-limit code on exceed');
assert.match(server, /if \(isAdminEmail\(email\)\) return;/, 'admin users must not consume one-time passes');
assert.match(server, /app\.post\('\/api\/encrypt',\s*requirePremium/, 'encrypt endpoint must enforce premium server-side');
assert.match(server, /app\.post\('\/api\/decrypt',\s*requirePremium/, 'decrypt endpoint must enforce premium server-side');
assert.match(server, /app\.post\('\/api\/convert\/pdf-to-hwp',\s*requirePremium/, 'pdf-to-hwp endpoint must enforce premium server-side');
assert.match(server, /consumeOneTimePassForRequest/, 'one-time premium passes must be consumed after successful premium use');
assert.match(server, /app\.get\('\/api\/usage',/, 'usage endpoint must be available for free-trial counters');
assert.match(server, /app\.post\('\/api\/usage\/consume',/, 'usage consume endpoint must support deterministic per-request trial decrement');
assert.match(server, /app\.post\('\/api\/contact'/, 'contact endpoint must be registered');
assert.match(server, /CONTACT_SMTP_NOT_CONFIGURED/, 'contact endpoint must fail deterministically when SMTP is not configured');
assert.match(server, /CONTACT_SEND_FAILED/, 'contact endpoint should report send failure on SMTP errors');
assert.match(server, /CONTACT_RECIPIENT_EMAIL/, 'contact endpoint should use configured recipient email');
assert.match(env, /SMTP_HOST=/, 'env example must document SMTP host');
assert.match(env, /SMTP_PORT=/, 'env example must document SMTP port');
assert.match(env, /SMTP_USER=/, 'env example must document SMTP user');
assert.match(env, /SMTP_PASS=/, 'env example must document SMTP pass');
assert.match(env, /SMTP_FROM=/, 'env example must document SMTP from');
assert.match(env, /SMTP_SECURE=/, 'env example must document SMTP secure mode');
assert.match(env, /CONTACT_EMAIL=/, 'env example must document contact recipient email');
assert.match(compose, /SMTP_HOST:/, 'docker compose must pass SMTP_HOST');
assert.match(compose, /SMTP_PORT:/, 'docker compose must pass SMTP_PORT');
assert.match(compose, /SMTP_USER:/, 'docker compose must pass SMTP_USER');
assert.match(compose, /SMTP_PASS:/, 'docker compose must pass SMTP_PASS');
assert.match(compose, /SMTP_FROM:/, 'docker compose must pass SMTP_FROM');
assert.match(compose, /SMTP_SECURE:/, 'docker compose must pass SMTP_SECURE');
assert.match(compose, /CONTACT_EMAIL:/, 'docker compose must pass CONTACT_EMAIL');
assert.match(server, /ownerEmail/, 'premium server-generated downloads must be tied to the requesting account');
assert.match(server, /DOWNLOAD_FORBIDDEN/, "download endpoint must reject access to another user\'s premium job output");
assert.match(server, /app\.get\('\/readyz'/, 'server must expose readiness endpoint for production probes');
assert.match(server, /app\.get\('\/healthz'/, 'server must expose lightweight liveness endpoint');

console.log('backend auth/premium static contract passed');
