# Coturn TURN server config — for Docker coturn/coturn:4.6-alpine
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
server-name=turn.ponslink.com
realm=ponslink.com
lt-cred-mech
use-auth-secret
static-auth-secret=63af752c07202c2ecc21594b05ef6c84399bf5c74d10195911cc6f3546b85d7f
cert=/etc/coturn-certs/fullchain.pem
pkey=/etc/coturn-certs/privkey.pem
no-tlsv1
no-tlsv1_1
log-file=stdout
verbose
fingerprint
no-multicast-peers
no-cli
stale-nonce=600
channel-lifetime=600
permission-lifetime=300
max-bps=1000000
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
